service: pusher-hue-api

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: post
          cors: true

plugins:
  - pusher
